In [439]:
import yaml
from datetime import datetime, timedelta, date

import yfinance as yf
import pandas as pd

In [440]:
df_stock = pd.read_excel("ListOfSecurities.xlsx")
df_stock.to_csv("ListOfSecurities.csv")

In [441]:
# Step 1: makes numeric headers
df_stock.columns = range(df_stock.shape[1]) 

# Step 2: Drop the 0th row
df_stock = df_stock.drop(0).reset_index(drop=True)

# Step 3: Make row 1 of df the header
df_stock.columns = df_stock.iloc[0]          # assign first row as header
df_stock = df_stock.drop(0).reset_index(drop=True)  # drop that header row from data

In [442]:
df_stock = df_stock[df_stock['Category']=="Equity"]
df_stock = df_stock[df_stock['Trading Currency']=="HKD"]

In [443]:
# df_stock

In [444]:
df_stock["Yahoo_Code"] = df_stock["Stock Code"] + ".HK"
df_stock["Yahoo_Code"] = df_stock["Yahoo_Code"].str.replace(r"^0", "", regex=True)

list_stock = []

for index, row in df_stock.iterrows():
    list_stock.append(row["Yahoo_Code"])

failed_HK_tickers = ['2927.HK', '2938.HK']

result = [x for x in list_stock if x not in failed_HK_tickers]

In [451]:
# response = yf.download(["0590.HK"], period='5d')
response2= yf.download(failed_HK_tickers, period='5d')

C:\Users\john\AppData\Local\Temp\ipykernel_33532\1596751797.py:2: FutureWarning: YF.download() has changed argument auto_adjust default to True
  response2= yf.download(failed_HK_tickers, period='5d')
[*********************100%***********************]  1 of 2 completed

2 Failed downloads:
['2927.HK', '2938.HK']: YFPricesMissingError('possibly delisted; no price data found  (period=5d) (Yahoo error = "No data found, symbol may be delisted")')

In [446]:
response = yf.download(result, period='5d')

C:\Users\john\AppData\Local\Temp\ipykernel_33532\966333546.py:1: FutureWarning: YF.download() has changed argument auto_adjust default to True
  response = yf.download(result, period='5d')
[*********************100%***********************]  2669 of 2669 completed

1 Failed download:
['0031.HK']: Timeout('Failed to perform, curl: (28) Connection timed out after 10014 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.')

In [452]:
response

Price      Adj Close      Close                                              \
Ticker       0031.HK    0001.HK    0002.HK   0003.HK    0004.HK     0005.HK
Date
2025-08-26       NaN        NaN        NaN       NaN        NaN         NaN
2025-08-27       NaN  51.150002  65.370003  6.880851  22.338572  100.099998
2025-08-28       NaN  51.500000  65.320473  6.920170  22.180000  100.599998
2025-08-29       NaN  51.349998  65.221428  6.890681  22.320000   99.750000
2025-09-01       NaN  51.700001  65.370003  6.930000  22.760000  100.000000
2025-09-02       NaN  51.750000  65.300003  6.910000  23.100000   99.750000

Price                                          ...     Volume            \
Ticker        0006.HK 0007.HK 0008.HK 0009.HK  ...    9989.HK   9990.HK
Date                                           ...
2025-08-26        NaN     NaN     NaN     NaN  ...        NaN       NaN
2025-08-27  50.250000   0.032    5.28   0.013  ...  3075500.0  576000.0
2025-08-28  50.500000   0.032    5.27   0.013  ...  2232500.0  776000.0
2025-08-29  50.750000   0.032    5.26   0.013  ...  1452500.0  538000.0
2025-09-01  50.849998   0.032    5.24   0.013  ...  2510500.0  835000.0
2025-09-02  50.849998     NaN    5.24     NaN  ...  3766500.0  324000.0

Price                                                                          \
Ticker      9991.HK     9992.HK    9993.HK     9995.HK    9996.HK     9997.HK
Date
2025-08-26      NaN         NaN        NaN         NaN        NaN         NaN
2025-08-27  35300.0  10514392.0  5515000.0   8447988.0  4842545.0   2690156.0
2025-08-28   7700.0   8162701.0  4112000.0   6452100.0  2793000.0  15819461.0
2025-08-29  57800.0   7126996.0  3731000.0  12304772.0  2265765.0   5420000.0
2025-09-01  35000.0  14402420.0  3543000.0   7051710.0  2255000.0   3834500.0
2025-09-02  40500.0   6038037.0  2914000.0   5930200.0  1543000.0   2575000.0

Price
Ticker      9998.HK    9999.HK
Date
2025-08-26      NaN        NaN
2025-08-27      0.0  7129558.0
2025-08-28  20000.0  5201556.0
2025-08-29      0.0  4724500.0
2025-09-01      0.0  3542605.0
2025-09-02   5000.0  5056351.0

[6 rows x 13346 columns]

In [453]:
failed_HK_tickers = ['2927.HK', '2938.HK']
with open("failed_HK_tickers.yaml", "w") as f:
    yaml.dump(failed_HK_tickers, f, default_flow_style=False, sort_keys=False)

In [454]:
response

Price      Adj Close      Close                                              \
Ticker       0031.HK    0001.HK    0002.HK   0003.HK    0004.HK     0005.HK
Date
2025-08-26       NaN        NaN        NaN       NaN        NaN         NaN
2025-08-27       NaN  51.150002  65.370003  6.880851  22.338572  100.099998
2025-08-28       NaN  51.500000  65.320473  6.920170  22.180000  100.599998
2025-08-29       NaN  51.349998  65.221428  6.890681  22.320000   99.750000
2025-09-01       NaN  51.700001  65.370003  6.930000  22.760000  100.000000
2025-09-02       NaN  51.750000  65.300003  6.910000  23.100000   99.750000

Price                                          ...     Volume            \
Ticker        0006.HK 0007.HK 0008.HK 0009.HK  ...    9989.HK   9990.HK
Date                                           ...
2025-08-26        NaN     NaN     NaN     NaN  ...        NaN       NaN
2025-08-27  50.250000   0.032    5.28   0.013  ...  3075500.0  576000.0
2025-08-28  50.500000   0.032    5.27   0.013  ...  2232500.0  776000.0
2025-08-29  50.750000   0.032    5.26   0.013  ...  1452500.0  538000.0
2025-09-01  50.849998   0.032    5.24   0.013  ...  2510500.0  835000.0
2025-09-02  50.849998     NaN    5.24     NaN  ...  3766500.0  324000.0

Price                                                                          \
Ticker      9991.HK     9992.HK    9993.HK     9995.HK    9996.HK     9997.HK
Date
2025-08-26      NaN         NaN        NaN         NaN        NaN         NaN
2025-08-27  35300.0  10514392.0  5515000.0   8447988.0  4842545.0   2690156.0
2025-08-28   7700.0   8162701.0  4112000.0   6452100.0  2793000.0  15819461.0
2025-08-29  57800.0   7126996.0  3731000.0  12304772.0  2265765.0   5420000.0
2025-09-01  35000.0  14402420.0  3543000.0   7051710.0  2255000.0   3834500.0
2025-09-02  40500.0   6038037.0  2914000.0   5930200.0  1543000.0   2575000.0

Price
Ticker      9998.HK    9999.HK
Date
2025-08-26      NaN        NaN
2025-08-27      0.0  7129558.0
2025-08-28  20000.0  5201556.0
2025-08-29      0.0  4724500.0
2025-09-01      0.0  3542605.0
2025-09-02   5000.0  5056351.0

[6 rows x 13346 columns]

In [455]:
df = response.T

In [456]:
df

Date               2025-08-26    2025-08-27    2025-08-28    2025-08-29  \
Price     Ticker
Adj Close 0031.HK         NaN           NaN           NaN           NaN
Close     0001.HK         NaN  5.115000e+01  5.150000e+01  5.135000e+01
          0002.HK         NaN  6.537000e+01  6.532047e+01  6.522143e+01
          0003.HK         NaN  6.880851e+00  6.920170e+00  6.890681e+00
          0004.HK         NaN  2.233857e+01  2.218000e+01  2.232000e+01
...                       ...           ...           ...           ...
Volume    9995.HK         NaN  8.447988e+06  6.452100e+06  1.230477e+07
          9996.HK         NaN  4.842545e+06  2.793000e+06  2.265765e+06
          9997.HK         NaN  2.690156e+06  1.581946e+07  5.420000e+06
          9998.HK         NaN  0.000000e+00  2.000000e+04  0.000000e+00
          9999.HK         NaN  7.129558e+06  5.201556e+06  4.724500e+06

Date                 2025-09-01    2025-09-02
Price     Ticker
Adj Close 0031.HK           NaN           NaN
Close     0001.HK  5.170000e+01  5.175000e+01
          0002.HK  6.537000e+01  6.530000e+01
          0003.HK  6.930000e+00  6.910000e+00
          0004.HK  2.276000e+01  2.310000e+01
...                         ...           ...
Volume    9995.HK  7.051710e+06  5.930200e+06
          9996.HK  2.255000e+06  1.543000e+06
          9997.HK  3.834500e+06  2.575000e+06
          9998.HK  0.000000e+00  5.000000e+03
          9999.HK  3.542605e+06  5.056351e+06

[13346 rows x 6 columns]

In [457]:
cols_open = list(df.T["Open"].columns)
cols_close = list(df.T["Close"].columns)

In [458]:
common = list(set(cols_open) & set(cols_close))
print(len(common))

2669

In [459]:
def last3_close_gt_open(open_series: pd.Series, close_series: pd.Series) -> bool:
    """
    Returns True if the last 3 days' closes are greater than opens.
    """
    diff = close_series - open_series
    last3 = diff.tail(3)
    check_diff = (last3 > 0).all()
    return check_diff

In [460]:
def last3_gt_prev(series: pd.Series) -> bool:
    last3 = series.tail(3)  # need 4 values to compare 3 consecutive increases
    return (last3.diff().tail(2) > 0).all()

In [461]:
c_list = []
for item in common:
    # print(item)
    close_series = df.T["Close"][item]
    open_series = df.T["Open"][item]

    check1 = last3_close_gt_open(open_series, close_series)
    check2 = last3_gt_prev(open_series)
    check3 = last3_gt_prev(close_series)

    if check1 and check2 and check3:
        c_list.append(item)

print(len(c_list))

65

In [462]:
c_list

['1530.HK',
 '0004.HK',
 '2336.HK',
 '2629.HK',
 '3306.HK',
 '3800.HK',
 '6821.HK',
 '1876.HK',
 '9606.HK',
 '2617.HK',
 '0883.HK',
 '0902.HK',
 '1167.HK',
 '0548.HK',
 '0991.HK',
 '2483.HK',
 '3833.HK',
 '2190.HK',
 '1571.HK',
 '1929.HK',
 '2185.HK',
 '0147.HK',
 '3788.HK',
 '0034.HK',
 '3658.HK',
 '3330.HK',
 '3369.HK',
 '2503.HK',
 '2257.HK',
 '2359.HK',
 '0857.HK',
 '2451.HK',
 '2161.HK',
 '1258.HK',
 '6990.HK',
 '0853.HK',
 '0975.HK',
 '1878.HK',
 '1501.HK',
 '2209.HK',
 '2565.HK',
 '0103.HK',
 '2499.HK',
 '6160.HK',
 '1050.HK',
 '2156.HK',
 '1581.HK',
 '6198.HK',
 '6181.HK',
 '9986.HK',
 '3759.HK',
 '0120.HK',
 '1168.HK',
 '1201.HK',
 '0950.HK',
 '8030.HK',
 '0241.HK',
 '0464.HK',
 '2197.HK',
 '2252.HK',
 '2268.HK',
 '8239.HK',
 '6998.HK',
 '2552.HK',
 '0616.HK']

In [463]:
response = yf.download(c_list, period='200d')

C:\Users\john\AppData\Local\Temp\ipykernel_33532\1833505185.py:1: FutureWarning: YF.download() has changed argument auto_adjust default to True
  response = yf.download(c_list, period='200d')
[*********************100%***********************]  65 of 65 completed

In [464]:
df2 = response

In [465]:
df2

Price           Close                                                      \
Ticker        0004.HK   0034.HK   0103.HK 0120.HK 0147.HK 0241.HK 0464.HK
Date
2024-11-11  22.849218  3.663005  0.333869   0.210   0.097    4.36   0.153
2024-11-12  22.505991  3.747320  0.329030   0.208   0.104    4.17   0.175
2024-11-13  22.358892  3.653637  0.338708   0.190   0.103    4.17   0.173
2024-11-14  22.604055  3.653637  0.348385   0.183   0.097    4.04   0.169
2024-11-15  23.143415  3.606796  0.348385   0.183   0.087    3.80   0.165
...               ...       ...       ...     ...     ...     ...     ...
2025-08-27  22.338572  3.400000  0.600000   0.123   0.221    5.42   0.720
2025-08-28  22.180000  3.400000  0.600000   0.120   0.200    5.38   0.720
2025-08-29  22.320000  3.400000  0.620000   0.122   0.218    5.46   0.730
2025-09-01  22.760000  3.430000  0.630000   0.123   0.430    5.84   0.790
2025-09-02  23.100000  3.470000  0.640000   0.125   0.530    6.11   0.860

Price                                 ...    Volume                    \
Ticker       0548.HK 0616.HK 0853.HK  ...   6160.HK  6181.HK  6198.HK
Date                                  ...
2024-11-11  6.865799   0.087    6.59  ...   1345361   375000  3323456
2024-11-12  6.740792   0.086    6.64  ...   2874488   757800  2829886
2024-11-13  6.731176   0.086    6.48  ...   2447438   333032   864000
2024-11-14  6.740792   0.087    6.29  ...   2107075   306300  2445727
2024-11-15  6.769639   0.087    6.18  ...   1104827   225200  1874000
...              ...     ...     ...  ...       ...      ...      ...
2025-08-27  7.120000   0.091   12.04  ...   5740490  1788371  2034454
2025-08-28  7.160000   0.100   11.78  ...   6371603  4696065  3839000
2025-08-29  7.150000   0.104   12.11  ...   7073994  1180822  7533210
2025-09-01  7.200000   0.124   14.77  ...   7702670  1489354  4222000
2025-09-02  7.240000   0.140   14.81  ...  11277555  1838905  2556000

Price
Ticker      6821.HK  6990.HK  6998.HK 8030.HK  8239.HK   9606.HK  9986.HK
Date
2024-11-11   238270   476438   125500       0    60000       NaN  2558000
2024-11-12   871890   307100    79000   20000    11300       NaN  3740000
2024-11-13   208600   276600   358000  250000        0       NaN  1136000
2024-11-14   121500   290574   361000       0        0       NaN  5710000
2024-11-15   102220   396411   219500   75000        0       NaN  2348000
...             ...      ...      ...     ...      ...       ...      ...
2025-08-27  1260540  2426446  3617000  300000  1092008  215958.0  1644000
2025-08-28  1065610   913520  2390000  356800   190000  146899.0  1720000
2025-08-29   788318   778804  1693500  262311  3166098  185600.0  4888000
2025-09-01   784700   650339  2526000  245300  1158640  365735.0  2088000
2025-09-02   655000   699946  2607500  190000  2130434  437000.0  4654000

[200 rows x 325 columns]

In [466]:
final_list = []

for item in c_list:
    price_series = df2["Close"][item]
    latest_ma = {
        "MA10":  price_series.tail(10).mean(),
        "MA20":  price_series.tail(20).mean(),
        "MA50":  price_series.tail(50).mean(),
        "MA150": price_series.tail(150).mean(),
        "MA200": price_series.tail(200).mean()
    }
    check_order = (latest_ma["MA10"] > latest_ma["MA20"] > latest_ma["MA50"] > latest_ma["MA150"] > latest_ma["MA200"])
    if check_order:
        final_list.append(item)

print(len(final_list))

28

In [467]:
final_list

['3306.HK',
 '1876.HK',
 '0883.HK',
 '0902.HK',
 '1167.HK',
 '0991.HK',
 '3833.HK',
 '2190.HK',
 '1929.HK',
 '2185.HK',
 '0147.HK',
 '3788.HK',
 '3330.HK',
 '3369.HK',
 '2257.HK',
 '2359.HK',
 '2451.HK',
 '1258.HK',
 '6990.HK',
 '0103.HK',
 '6160.HK',
 '1050.HK',
 '2156.HK',
 '8030.HK',
 '0241.HK',
 '0464.HK',
 '2197.HK',
 '6998.HK']

In [468]:
for item in final_list:
    data = yf.Ticker(item).info
    # print(data.get("trailingPE"))
    # print(data.get("forwardPE"))
    # if data.get("forwardPE"):
    #     print(item)
    report = score_stock(data)
    if report.get("score") >= 70:
        print(item, report.get("score"))
        print(report.get("verdict"))

3306.HK 75
['Cheap valuation', 'Strong cash flow', 'High dividend yield', 'High efficiency (ROE)']
0883.HK 80
['Cheap valuation', 'Strong cash flow', 'High dividend yield', 'Healthy liquidity', 'High efficiency (ROE)']
3330.HK 75
['Cheap valuation', 'High dividend yield', 'High debt load', 'High efficiency (ROE)', 'Strong revenue growth', 'Explosive earnings growth']
3369.HK 75
['Cheap valuation', 'Strong cash flow', 'High dividend yield', 'Healthy liquidity']
2359.HK 70
['Expensive valuation', 'Strong cash flow', 'High dividend yield', 'Healthy liquidity', 'High efficiency (ROE)', 'Strong revenue growth', 'Explosive earnings growth']
1258.HK 75
['Cheap valuation', 'High dividend yield', 'Healthy liquidity', 'High efficiency (ROE)']
1050.HK 70
['Strong cash flow', 'High dividend yield', 'High efficiency (ROE)', 'Strong revenue growth']
2156.HK 70
['High cash reserves', 'High dividend yield', 'Healthy liquidity', 'High efficiency (ROE)']

In [429]:
dat = yf.Ticker("3383.HK")

In [430]:
stock_health_check(dat.info)

{'Trailing P/E': None,
 'Forward P/E': -0.6521739,
 'Cash Flow per Share': None,
 'EPS (TTM)': -3.38,
 'Current Ratio': 0.857,
 'Quick Ratio': 0.389,
 'Return on Assets': -0.00681,
 'Return on Equity': -0.37449002,
 'Dividend Yield %': None,
 'Payout Ratio': 0.0,
 'Debt-to-Equity': 144.706,
 'Verdict': ['Cheap valuation']}

In [400]:
def stock_health_check(data: dict) -> dict:
    results = {}

    # --- P/E Ratios ---
    results["Trailing P/E"] = data.get("trailingPE")
    results["Forward P/E"] = data.get("forwardPE")

    # --- Cash Flow per Share ---
    ocf = data.get("operatingCashflow")
    shares = data.get("sharesOutstanding")
    if ocf and shares:
        results["Cash Flow per Share"] = ocf / shares
    else:
        results["Cash Flow per Share"] = None

    # --- EPS ---
    results["EPS (TTM)"] = data.get("trailingEps")

    # --- Liquidity ---
    results["Current Ratio"] = data.get("currentRatio")
    results["Quick Ratio"] = data.get("quickRatio")

    # --- Returns ---
    results["Return on Assets"] = data.get("returnOnAssets")
    results["Return on Equity"] = data.get("returnOnEquity")

    # --- Dividend ---
    results["Dividend Yield %"] = data.get("dividendYield")
    results["Payout Ratio"] = data.get("payoutRatio")

    # --- Debt ---
    results["Debt-to-Equity"] = data.get("debtToEquity")

    # --- Basic Health Verdict ---
    verdict = []
    if results["Forward P/E"] and results["Forward P/E"] < 15:
        verdict.append("Cheap valuation")
    if results["Cash Flow per Share"] and results["EPS (TTM)"] and results["Cash Flow per Share"] > results["EPS (TTM)"]:
        verdict.append("Strong cash flow quality")
    if results["Current Ratio"] and results["Current Ratio"] > 1.2:
        verdict.append("Healthy liquidity")
    if results["Return on Equity"] and results["Return on Equity"] > 0.15:
        verdict.append("High efficiency (ROE)")
    if results["Dividend Yield %"] and results["Dividend Yield %"] > 0.05:
        verdict.append("Attractive dividend")

    results["Verdict"] = verdict
    return results

In [218]:
report = stock_health_check(dat.info)
for k, v in report.items():
    print(f"{k}: {v}")

Trailing P/E: 28.59375
Forward P/E: None
Cash Flow per Share: None
EPS (TTM): 0.32
Current Ratio: 1.089
Quick Ratio: 0.814
Return on Assets: 0.01918
Return on Equity: 0.10195
Dividend Yield %: 1.67
Payout Ratio: 0.0
Debt-to-Equity: 81.457
Verdict: ['Attractive dividend']

In [ ]:
3306 - JNBY Design
1876 -No
883 - CNOOC

In [220]:
MarketCap = []

count = 0

for item in final_list:
    count += 1
    dat = yf.Ticker(item)
    if not dat.info.get("marketCap"):
        print(count, item)
        
    if dat.info.get("marketCap") and dat.info.get("marketCap") > 100000000:
        vol_series = df2["Volume"][item]
        avg_3 = vol_series.tail(3).mean()
        avg_20 = vol_series.tail(20).mean()
        check = avg_3 > avg_20
        if check:
            MarketCap.append(item)
        # print(check)
    
MarketCap.sort()

In [221]:
len(MarketCap)

15

In [354]:
def stock_profile(data: dict) -> dict:
    results = {}

    # --- Extract Key Values ---
    trailing_pe = data.get("trailingPE")
    forward_pe = data.get("forwardPE")
    eps = data.get("trailingEps")
    ocf = data.get("operatingCashflow")
    shares = data.get("sharesOutstanding")
    cash_per_share = data.get("totalCashPerShare")
    dividend_yield = data.get("dividendYield")
    payout_ratio = data.get("payoutRatio")
    current_ratio = data.get("currentRatio")
    quick_ratio = data.get("quickRatio")
    roe = data.get("returnOnEquity")
    roa = data.get("returnOnAssets")
    debt_to_equity = data.get("debtToEquity")
    revenue_growth = data.get("revenueGrowth")
    earnings_growth = data.get("earningsGrowth")
    profit_margin = data.get("profitMargins")

    # --- Derived Values ---
    if ocf and shares:
        cash_flow_per_share = ocf / shares
    else:
        cash_flow_per_share = None

    # Save key outputs
    results.update({
        "Trailing P/E": trailing_pe,
        "Forward P/E": forward_pe,
        "EPS (TTM)": eps,
        "Cash Flow per Share": cash_flow_per_share,
        "Cash per Share": cash_per_share,
        "Dividend Yield %": dividend_yield,
        "Payout Ratio": payout_ratio,
        "Current Ratio": current_ratio,
        "Quick Ratio": quick_ratio,
        "ROE": roe,
        "ROA": roa,
        "Debt-to-Equity": debt_to_equity,
        "Revenue Growth": revenue_growth,
        "Earnings Growth": earnings_growth,
        "Profit Margin": profit_margin
    })

    # --- Scoring ---
    verdict = []

    # Valuation
    if forward_pe and forward_pe < 15:
        verdict.append("Cheap valuation")
    elif trailing_pe and trailing_pe > 20:
        verdict.append("Expensive valuation")

    # Cash / Dividend
    if cash_flow_per_share and eps and cash_flow_per_share > eps:
        verdict.append("Strong cash flow quality")
    if cash_per_share and data.get("currentPrice") and cash_per_share > data["currentPrice"] * 0.4:
        verdict.append("High cash reserves")
    if dividend_yield and dividend_yield > 0.05:
        verdict.append("High dividend yield")
    elif dividend_yield and dividend_yield < 0.02:
        verdict.append("Low dividend")

    # Liquidity
    if current_ratio and current_ratio < 1.2:
        verdict.append("Weak liquidity")
    elif current_ratio and current_ratio > 1.5:
        verdict.append("Healthy liquidity")

    # Profitability
    if roe and roe > 0.15:
        verdict.append("High efficiency (ROE)")
    if roa and roa < 0.03:
        verdict.append("Low ROA")
    if profit_margin and profit_margin < 0.05:
        verdict.append("Thin margins")

    # Debt
    if debt_to_equity and debt_to_equity > 70:
        verdict.append("High debt load")

    # Growth
    if revenue_growth and revenue_growth > 0.15:
        verdict.append("Strong revenue growth")
    if earnings_growth and earnings_growth > 0.3:
        verdict.append("Explosive earnings growth")

    results["Verdict"] = verdict

    # --- Classification ---
    profile = "Balanced"
    if "Cheap valuation" in verdict and ("High dividend yield" in verdict or "Strong cash flow quality" in verdict):
        profile = "Cash Cow / Value"
    elif "Expensive valuation" in verdict and ("Strong revenue growth" in verdict or "Explosive earnings growth" in verdict):
        profile = "Growth Bet"
    elif "Weak liquidity" in verdict or "High debt load" in verdict or "Thin margins" in verdict:
        profile = "High Risk"

    results["Profile"] = profile
    return results

In [408]:
def score_stock(data: dict) -> dict:
    # Extract metrics
    metrics = {
        "forward_pe": data.get("forwardPE"),
        "trailing_pe": data.get("trailingPE"),
        "eps": data.get("trailingEps"),
        "ocf": data.get("operatingCashflow"),
        "shares": data.get("sharesOutstanding"),
        "cash_per_share": data.get("totalCashPerShare"),
        "current_price": data.get("currentPrice"),
        "div_yield": data.get("dividendYield"),
        "payout": data.get("payoutRatio"),
        "curr_ratio": data.get("currentRatio"),
        "quick_ratio": data.get("quickRatio"),
        "roe": data.get("returnOnEquity"),
        "roa": data.get("returnOnAssets"),
        "debt_eq": data.get("debtToEquity"),
        "rev_growth": data.get("revenueGrowth"),
        "earnings_growth": data.get("earningsGrowth"),
        "profit_margin": data.get("profitMargins")
    }

    # Compute cash flow per share
    if metrics["ocf"] and metrics["shares"]:
        metrics["cfps"] = metrics["ocf"] / metrics["shares"]
    else:
        metrics["cfps"] = None

    verdict = []
    score = 50  # neutral starting point

    # Valuation adjustments
    if metrics["forward_pe"] and metrics["forward_pe"] < 15:
        verdict.append("Cheap valuation"); score += 10
    if metrics["trailing_pe"] and metrics["trailing_pe"] != "Infinity"  and metrics["trailing_pe"] > 20:
        verdict.append("Expensive valuation"); score -= 10

    # Cash and dividend
    if metrics["cfps"] and metrics["eps"] and metrics["cfps"] > metrics["eps"]:
        verdict.append("Strong cash flow"); score += 5
    if metrics["cash_per_share"] and metrics["current_price"] and metrics["cash_per_share"] > metrics["current_price"] * 0.4:
        verdict.append("High cash reserves"); score += 5
    if metrics["div_yield"] and metrics["div_yield"] > 0.05:
        verdict.append("High dividend yield"); score += 5
    elif metrics["div_yield"] and metrics["div_yield"] < 0.02:
        verdict.append("Low dividend"); score -= 5

    # Liquidity & debt
    if metrics["curr_ratio"] and metrics["curr_ratio"] < 1:
        verdict.append("Weak liquidity"); score -= 5
    elif metrics["curr_ratio"] and metrics["curr_ratio"] > 1.5:
        verdict.append("Healthy liquidity"); score += 5
    if metrics["debt_eq"] and metrics["debt_eq"] > 70:
        verdict.append("High debt load"); score -= 5

    # Profitability
    if metrics["roe"] and metrics["roe"] > 0.15:
        verdict.append("High efficiency (ROE)"); score += 5
    if metrics["roa"] and metrics["roa"] < 0.03:
        verdict.append("Low ROA"); score -= 5
    if metrics["profit_margin"] and metrics["profit_margin"] < 0.05:
        verdict.append("Thin margins"); score -= 5

    # Growth factors
    if metrics["rev_growth"] and metrics["rev_growth"] > 0.15:
        verdict.append("Strong revenue growth"); score += 5
    if metrics["earnings_growth"] and metrics["earnings_growth"] > 0.3:
        verdict.append("Explosive earnings growth"); score += 5

    # Bound the score
    score = max(0, min(100, score))

    # Profile classification
    profile = "Balanced"
    if "Cheap valuation" in verdict and ("High dividend yield" in verdict or "Strong cash flow" in verdict):
        profile = "Cash Cow / Value"
    elif "Expensive valuation" in verdict and ("Strong revenue growth" in verdict or "Explosive earnings growth" in verdict):
        profile = "Growth Bet"
    if "Weak liquidity" in verdict or "High debt load" in verdict or "Thin margins" in verdict:
        profile = "High Risk"

    return {"score": score, "verdict": verdict, "profile": profile}

In [359]:
MarketCap

['0147.HK',
 '0241.HK',
 '0883.HK',
 '0991.HK',
 '1050.HK',
 '1167.HK',
 '1258.HK',
 '2190.HK',
 '2197.HK',
 '2257.HK',
 '2378.HK',
 '3306.HK',
 '3330.HK',
 '3788.HK',
 '6160.HK']

In [409]:
for item in MarketCap:
    dat = yf.Ticker(item)
    report = score_stock(dat.info)
    if report.get('score') >= 70:
        print(item)

0883.HK
1050.HK
1258.HK
2378.HK
3306.HK
3330.HK

In [431]:
dat = yf.Ticker("3383.HK")
report = score_stock(dat.info)
for k, v in report.items():
    print(f"{k}: {v}")

score: 45
verdict: ['Cheap valuation', 'High cash reserves', 'Weak liquidity', 'High debt load', 'Low ROA', 'Thin margins']
profile: High Risk

In [368]:
dat.info

{'address1': '19 Pandan Road',
 'city': 'Singapore',
 'zip': '609271',
 'country': 'Singapore',
 'phone': '65 6264 3833',
 'fax': '65 6266 1473',
 'website': 'https://www.aslmarine.com',
 'industry': 'Aerospace & Defense',
 'industryKey': 'aerospace-defense',
 'industryDisp': 'Aerospace & Defense',
 'sector': 'Industrials',
 'sectorKey': 'industrials',
 'sectorDisp': 'Industrials',
 'longBusinessSummary': 'ASL Marine Holdings Ltd., provides marine services in Singapore, Indonesia, Asia Pacific, South Asia, Europe, the Middle East, and Australia. The company offers shiprepair and conversion, dredge engineering, shipchartering, shipbuilding, and other marine related services. It also offers retrofitting, extending vessel life, repairing large ships, offshore oil and gas vessel, LNG conversion, and ship repair conversion technology services. In addition, the company develops low emission, hybrid, and electric vessel technology. Further, it provides decommissioning, upcycling, waste management, and other support services to offshore projects. ASL Marine Holdings Ltd. was founded in 1974 and is headquartered in Singapore.',
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Kok Tian  Ang',
   'age': 63,
   'title': 'Chairman, CEO & MD',
   'yearBorn': 1961,
   'fiscalYear': 2024,
   'totalPay': 440000,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Ah Nui  Ang',
   'age': 61,
   'title': 'Deputy MD & Executive Director',
   'yearBorn': 1963,
   'fiscalYear': 2024,
   'totalPay': 426000,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Kok Leong  Ang',
   'age': 56,
   'title': 'Executive Director',
   'yearBorn': 1968,
   'fiscalYear': 2024,
   'totalPay': 313000,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Sin Liu  Ang',
   'age': 89,
   'title': 'Founder & Advisor',
   'yearBorn': 1935,
   'fiscalYear': 2024,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Kai Kheng  Koh',
   'age': 49,
   'title': 'Company Secretary',
   'yearBorn': 1975,
   'fiscalYear': 2024,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'compensationAsOfEpochDate': 1735603200,
 'irWebsite': 'http://www.aslmarine.com/investor.htm',
 'executiveTeam': [],
 'maxAge': 86400,
 'priceHint': 4,
 'previousClose': 0.112,
 'open': 0.114,
 'dayLow': 0.114,
 'dayHigh': 0.144,
 'regularMarketPreviousClose': 0.112,
 'regularMarketOpen': 0.114,
 'regularMarketDayLow': 0.114,
 'regularMarketDayHigh': 0.144,
 'exDividendDate': 1763078400,
 'payoutRatio': 0.0,
 'fiveYearAvgDividendYield': 2.44,
 'beta': 0.379,
 'trailingPE': 'Infinity',
 'volume': 18393600,
 'regularMarketVolume': 18393600,
 'averageVolume': 941530,
 'averageVolume10days': 3239460,
 'averageDailyVolume10Day': 3239460,
 'bid': 0.144,
 'ask': 0.143,
 'bidSize': 0,
 'askSize': 0,
 'marketCap': 142261776,
 'fiftyTwoWeekLow': 0.05,
 'fiftyTwoWeekHigh': 0.144,
 'priceToSalesTrailing12Months': 0.4150357,
 'fiftyDayAverage': 0.06794,
 'twoHundredDayAverage': 0.06176,
 'trailingAnnualDividendRate': 0.002,
 'trailingAnnualDividendYield': 0.017857144,
 'currency': 'SGD',
 'tradeable': False,
 'enterpriseValue': 272473120,
 'profitMargins': 0.01132,
 'floatShares': 251605752,
 'sharesOutstanding': 987929024,
 'heldPercentInsiders': 0.74343,
 'heldPercentInstitutions': 0.0,
 'impliedSharesOutstanding': 987929024,
 'bookValue': 0.113,
 'priceToBook': 1.2743362,
 'lastFiscalYearEnd': 1719705600,
 'nextFiscalYearEnd': 1751241600,
 'mostRecentQuarter': 1735603200,
 'netIncomeToCommon': 3879000,
 'trailingEps': 0.0,
 'lastSplitFactor': '14:10',
 'lastSplitDate': 1292976000,
 'enterpriseToRevenue': 0.795,
 'enterpriseToEbitda': 4.394,
 '52WeekChange': 0.93103445,
 'SandP52WeekChange': 0.16844666,
 'lastDividendValue': 0.002,
 'lastDividendDate': 1763078400,
 'quoteType': 'EQUITY',
 'currentPrice': 0.144,
 'recommendationKey': 'none',
 'totalCash': 19563000,
 'totalCashPerShare': 0.02,
 'ebitda': 62008000,
 'totalDebt': 210208000,
 'quickRatio': 0.379,
 'currentRatio': 0.68,
 'totalRevenue': 342769984,
 'debtToEquity': 211.424,
 'revenuePerShare': 0.408,
 'returnOnAssets': 0.02888,
 'returnOnEquity': 0.04783,
 'grossProfits': 47082000,
 'freeCashflow': -38809000,
 'operatingCashflow': 45945000,
 'revenueGrowth': -0.027,
 'grossMargins': 0.13736,
 'ebitdaMargins': 0.18090001,
 'operatingMargins': 0.08163,
 'financialCurrency': 'SGD',
 'symbol': 'A04.SI',
 'language': 'en-US',
 'region': 'US',
 'typeDisp': 'Equity',
 'quoteSourceName': 'Delayed Quote',
 'triggerable': False,
 'customPriceAlertConfidence': 'LOW',
 'regularMarketChangePercent': 28.571419,
 'regularMarketPrice': 0.144,
 'marketState': 'POSTPOST',
 'corporateActions': [],
 'regularMarketTime': 1756803861,
 'exchange': 'SES',
 'messageBoardId': 'finmb_8292719',
 'exchangeTimezoneName': 'Asia/Singapore',
 'exchangeTimezoneShortName': 'SGT',
 'gmtOffSetMilliseconds': 28800000,
 'market': 'sg_market',
 'esgPopulated': False,
 'hasPrePostMarketData': False,
 'firstTradeDateMilliseconds': 1047862800000,
 'regularMarketChange': 0.03199999,
 'regularMarketDayRange': '0.114 - 0.144',
 'fullExchangeName': 'SES',
 'averageDailyVolume3Month': 941530,
 'fiftyTwoWeekLowChange': 0.094,
 'fiftyTwoWeekLowChangePercent': 1.8799999,
 'fiftyTwoWeekRange': '0.05 - 0.144',
 'fiftyTwoWeekHighChange': 0.0,
 'fiftyTwoWeekHighChangePercent': 0.0,
 'fiftyTwoWeekChangePercent': 93.10345,
 'earningsTimestampStart': 1756281600,
 'earningsTimestampEnd': 1756713600,
 'isEarningsDateEstimate': True,
 'epsTrailingTwelveMonths': 0.0,
 'fiftyDayAverageChange': 0.07606,
 'fiftyDayAverageChangePercent': 1.1195172,
 'twoHundredDayAverageChange': 0.08223999,
 'twoHundredDayAverageChangePercent': 1.331606,
 'sourceInterval': 20,
 'exchangeDataDelayedBy': 10,
 'shortName': 'ASL Marine',
 'longName': 'ASL Marine Holdings Ltd.',
 'cryptoTradeable': False,
 'trailingPegRatio': None}

In [369]:
print(dat.info.get('trailingPE'))
print(dat.info.get('forwardPE'))
print(dat.info.get('debtToEquity'))

Infinity
None
211.424

In [336]:
dat.info

{'address1': 'Singapore Post Centre',
 'address2': 'No. 07-31 10 Eunos Road 8',
 'city': 'Singapore',
 'zip': '408600',
 'country': 'Singapore',
 'phone': '65 6838 3388',
 'fax': '65 6732 8428',
 'website': 'https://www.singtel.com',
 'industry': 'Telecom Services',
 'industryKey': 'telecom-services',
 'industryDisp': 'Telecom Services',
 'sector': 'Communication Services',
 'sectorKey': 'communication-services',
 'sectorDisp': 'Communication Services',
 'longBusinessSummary': 'Singapore Telecommunications Limited, together with its subsidiaries, provides telecommunication services to consumers and small businesses in Singapore, Australia, and internationally. It operates through Optus, Singtel Singapore, NCS, and Digital InfraCo segments. The company provides mobile, equipment sales, fixed voice and data, satellite, ICT and managed services; pay television, content and digital services, and ICT services; and technology services to clients through its Gov+, Enterprise, and Telco+ groups. It also offers regional data center services under Nxera; satellite carrier services; and Paragon, a digital acceleration platform for 5G multi-access edge compute and cloud orchestration, as well as AI Cloud Service through RE:AI. In addition, the company offers services comprising insurance, my Singtel app, my smart network, GXS bank, dash, Singtel paylater, and telephony services. The company was incorporated in 1992 and is headquartered in Singapore.',
 'fullTimeEmployees': 21000,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Kuan Moon  Yuen',
   'age': 57,
   'title': 'CEO, Executive Non-Independent Director & Member of Optus Advisory Committee',
   'yearBorn': 1967,
   'fiscalYear': 2025,
   'totalPay': 3631090,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Tao Yih  Lang',
   'age': 52,
   'title': 'Group Chief Financial Officer',
   'yearBorn': 1972,
   'fiscalYear': 2025,
   'totalPay': 1228250,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Jorge Capelas  Fernandes',
   'title': 'Group Chief Technology Officer',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Siew Wing  Woo',
   'age': 60,
   'title': 'Group Chief Information Officer & Group Chief Digital Officer',
   'yearBorn': 1964,
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Yang Fong Sin',
   'title': 'Vice President of Investor Relations',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Lian  Pek',
   'title': 'Vice President of Group Corporate Communications & Brand',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Chris  Smith',
   'title': 'Head of Digital Sales & Service - Optus',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Aileen  Tan',
   'age': 57,
   'title': 'Group Chief People & Sustainability Officer',
   'yearBorn': 1967,
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Yoong Keong  Lew',
   'age': 69,
   'title': 'CEO of Group Strategy & Business Development and Country Chief Officer of Thailand',
   'yearBorn': 1955,
   'fiscalYear': 2025,
   'totalPay': 2327028,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Mark  Chong',
   'age': 61,
   'title': 'Group Chief Corporate Officer',
   'yearBorn': 1963,
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'auditRisk': 3,
 'boardRisk': 1,
 'compensationRisk': 4,
 'shareHolderRightsRisk': 6,
 'overallRisk': 1,
 'governanceEpochDate': 1756684800,
 'compensationAsOfEpochDate': 1767139200,
 'executiveTeam': [],
 'maxAge': 86400,
 'priceHint': 4,
 'previousClose': 4.33,
 'open': 4.35,
 'dayLow': 4.32,
 'dayHigh': 4.39,
 'regularMarketPreviousClose': 4.33,
 'regularMarketOpen': 4.35,
 'regularMarketDayLow': 4.32,
 'regularMarketDayHigh': 4.39,
 'exDividendDate': 1418947200,
 'payoutRatio': 0.0,
 'beta': 0.419,
 'trailingPE': 18.208334,
 'volume': 188820,
 'regularMarketVolume': 188820,
 'averageVolume': 156590,
 'averageVolume10days': 211280,
 'averageDailyVolume10Day': 211280,
 'bid': 4.37,
 'ask': 4.38,
 'bidSize': 0,
 'askSize': 0,
 'marketCap': 72160059392,
 'fiftyTwoWeekLow': 2.89,
 'fiftyTwoWeekHigh': 4.39,
 'priceToSalesTrailing12Months': 5.1086407,
 'fiftyDayAverage': 4.0402,
 'twoHundredDayAverage': 3.58265,
 'trailingAnnualDividendRate': 0.0,
 'trailingAnnualDividendYield': 0.0,
 'currency': 'SGD',
 'tradeable': False,
 'enterpriseValue': 80413966336,
 'profitMargins': 0.4396,
 'floatShares': 8012056471,
 'sharesOutstanding': 37244100,
 'heldPercentInsiders': 0.05705,
 'heldPercentInstitutions': 0.68874,
 'impliedSharesOutstanding': 16512600064,
 'bookValue': 1.508,
 'priceToBook': 2.897878,
 'lastFiscalYearEnd': 1743379200,
 'nextFiscalYearEnd': 1774915200,
 'mostRecentQuarter': 1751241600,
 'earningsQuarterlyGrowth': 3.177,
 'netIncomeToCommon': 6209399808,
 'trailingEps': 0.24,
 'enterpriseToRevenue': 5.693,
 'enterpriseToEbitda': 23.66,
 '52WeekChange': 0.39677417,
 'SandP52WeekChange': 0.16844666,
 'lastDividendValue': 0.068,
 'lastDividendDate': 1418947200,
 'quoteType': 'EQUITY',
 'currentPrice': 4.37,
 'recommendationKey': 'none',
 'totalCash': 2773499904,
 'totalCashPerShare': 0.168,
 'ebitda': 3398775040,
 'totalDebt': 11671700480,
 'totalRevenue': 14125100032,
 'debtToEquity': 44.967,
 'revenuePerShare': 0.856,
 'grossProfits': 3581199872,
 'revenueGrowth': -0.006,
 'grossMargins': 0.25353,
 'ebitdaMargins': 0.24062,
 'operatingMargins': 0.12353,
 'financialCurrency': 'SGD',
 'symbol': 'Z77.SI',
 'language': 'en-US',
 'region': 'US',
 'typeDisp': 'Equity',
 'quoteSourceName': 'Delayed Quote',
 'triggerable': False,
 'customPriceAlertConfidence': 'LOW',
 'shortName': 'Singtel 10',
 'longName': 'Singapore Telecommunications Limited',
 'regularMarketChangePercent': 0.92378664,
 'regularMarketPrice': 4.37,
 'marketState': 'REGULAR',
 'corporateActions': [],
 'regularMarketTime': 1756799510,
 'exchange': 'SES',
 'messageBoardId': 'finmb_112384',
 'exchangeTimezoneName': 'Asia/Singapore',
 'exchangeTimezoneShortName': 'SGT',
 'gmtOffSetMilliseconds': 28800000,
 'market': 'sg_market',
 'esgPopulated': False,
 'hasPrePostMarketData': False,
 'firstTradeDateMilliseconds': 1099616400000,
 'regularMarketChange': 0.03999996,
 'regularMarketDayRange': '4.32 - 4.39',
 'fullExchangeName': 'SES',
 'averageDailyVolume3Month': 156590,
 'fiftyTwoWeekLowChange': 1.4799998,
 'fiftyTwoWeekLowChangePercent': 0.51211065,
 'fiftyTwoWeekRange': '2.89 - 4.39',
 'fiftyTwoWeekHighChange': -0.01999998,
 'fiftyTwoWeekHighChangePercent': -0.0045558047,
 'fiftyTwoWeekChangePercent': 39.677418,
 'earningsTimestampStart': 1747873800,
 'earningsTimestampEnd': 1747873800,
 'earningsCallTimestampStart': 1731495540,
 'earningsCallTimestampEnd': 1731495540,
 'isEarningsDateEstimate': False,
 'epsTrailingTwelveMonths': 0.24,
 'fiftyDayAverageChange': 0.32979965,
 'fiftyDayAverageChangePercent': 0.08162953,
 'twoHundredDayAverageChange': 0.78734994,
 'twoHundredDayAverageChangePercent': 0.21976748,
 'sourceInterval': 20,
 'exchangeDataDelayedBy': 10,
 'cryptoTradeable': False,
 'trailingPegRatio': 4.4374}

In [152]:
print(MarketCap.sort())

None

In [ ]:
81
1121
1818
1741
1729

In [183]:
final_list

['0020.HK',
 '0142.HK',
 '0270.HK',
 '0400.HK',
 '0881.HK',
 '1086.HK',
 '1087.HK',
 '1112.HK',
 '1121.HK',
 '1133.HK',
 '1292.HK',
 '1828.HK',
 '1913.HK',
 '1979.HK',
 '2590.HK',
 '3393.HK',
 '3669.HK',
 '6805.HK',
 '8635.HK',
 '9660.HK']

In [47]:
open_series = dat["Open"]["AAPL"]
close_series = dat["Close"]["AAPL"]

pct_change_open_close = ((close_series - open_series) / open_series) * 100
print(pct_change_open_close)

Date
2025-08-25    0.300251
2025-08-26    1.075507
2025-08-27    0.822363
2025-08-28    0.753830
2025-08-29   -0.159131
Name: AAPL, dtype: float64

In [48]:
def check_trend(pct_series: pd.Series):
    # condition 1: 2 consecutive >= +1%
    cond1 = ((pct_series >= 1).astype(int)
             .rolling(2).sum() >= 2).any()

    # condition 2: 3 consecutive > 0
    cond2 = ((pct_series > 0).astype(int)
             .rolling(3).sum() >= 3).any()

    return cond1, cond2

In [49]:
pct_change_open_close = ((close_series - open_series) / open_series) * 100
c1, c2 = check_trend(pct_change_open_close)

print("2 consecutive >= +1%:", c1)
print("3 consecutive > 0:", c2)

2 consecutive >= +1%: False
3 consecutive > 0: True